---
title: "Statistical ANOVA Late Payments Abe Archer"
author: "Abe Archer"
date: "2024-04-19"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(tidyverse)
library(ggplot2)
library(stats)

library(car)
dataset = '/Users/abearcher/Spring2024/DASC1223H/Late_payments_Abes.csv'
df <- read.csv(dataset)

loanamount_installment <- aov(installment ~ loan_amnt,
               data = df
)

```

```{r}
#This is a histogram of the loan amount vs the installments
hist(loanamount_installment$residuals, main = "Histogram of Loans / Installments")

```

```{r}
#This shows the qqplot of loanamount vs installments
qqPlot(loanamount_installment$residuals,
       id = FALSE)

```

```{r}
loanamount_annualinc <- aov(annual_inc ~ loan_amnt,
               data = df
)
```

```{r}
#This is a histogram of the loan amount vs the installments
hist(loanamount_annualinc$residuals, main = "Histogram of Loans / Annual Income")

```

```{r}
#This shows the qqplot of installment vs annual income
qqPlot(loanamount_annualinc$residuals,
       id = FALSE)

```

```{r}
installments_annualinc <- aov(annual_inc ~ installment,
               data = df
)
```

```{r}
#This is a histogram of the annual income vs the installments
hist(installments_annualinc$residuals, main = "Histogram of Installments / Annual Income")

```
```{r}
#This shows the qqplot of installment vs annual income
qqPlot(installments_annualinc$residuals,
       id = FALSE)

```

```{r}
interest_annualinc <- aov(annual_inc ~ int_rate,
               data = df
)
```

```{r}
#This is a histogram of the annual income vs the installments
hist(interest_annualinc$residuals, main = "Histogram of Interest Rate / Annual Income")

```

```{r}
#This shows the qqplot of installment vs annual income
qqPlot(interest_annualinc$residuals,
       id = FALSE)

```

```{r}
interest_loanamount <- aov(loan_amnt ~ int_rate,
               data = df
)
```

```{r}
#This is a histogram of the annual income vs the installments
hist(interest_loanamount$residuals, main = "Histogram of Interest Rate / Loan Amount")

```

```{r}
#This shows the qqplot of installment vs annual income
qqPlot(interest_loanamount$residuals,
       id = FALSE)

```
```{r}
funded_loanamount <- aov(loan_amnt ~ funded_amnt,
               data = df
)
```

```{r}
#This is a histogram of the annual income vs the installments
hist(funded_loanamount$residuals, main = "Histogram of Funded Amount / Loan Amount")

```

```{r}
#This shows the qqplot of installment vs annual income
qqPlot(funded_loanamount$residuals,
       id = FALSE)

```

```{r}
dti_loanamount <- aov(loan_amnt ~ dti,
               data = df
)
```

```{r}
#This is a histogram of the annual income vs the installments
hist(dti_loanamount$residuals, main = "Histogram of DTI / Loan Amount")

```

```{r}
#This shows the qqplot of installment vs annual income
qqPlot(dti_loanamount$residuals,
       id = FALSE)

```


```{r}
outstanding_loanamount <- aov(loan_amnt ~ out_prncp,
               data = df
)
summary_outstandingloanamount <- summary(outstanding_loanamount)

# Extract the residual standard error
summary_outstandingloanamount

mse <- summary(outstanding_loanamount)[[1]]$'Mean Sq'[2]

# Print mean squared error
print(mse)
```

```{r}
#This is a histogram of the annual income vs the installments
hist(outstanding_loanamount$residuals, main = "Outstanding Principal Amount  / Loan Amount")

```

```{r}
#This shows the qqplot of installment vs annual income
qqPlot(outstanding_loanamount$residuals,
       id = FALSE)

```


```{r}
outstanding_interest <- aov(int_rate ~ out_prncp,
               data = df
)
outstanding_interest_sum <- summary(outstanding_interest)
outstanding_interest_sum
```

```{r}
#This is a histogram of the annual income vs the installments
hist(outstanding_interest$residuals, main = "Outstanding Principal Amount  / Interest Rate")

```

```{r}
#This shows the qqplot of installment vs annual income
qqPlot(outstanding_interest$residuals,
       id = FALSE)

```


```{r}
dti_interest <- aov(int_rate ~ dti,
               data = df
)
summary_dti_interest <- summary(dti_interest)

# Extract the residual standard error
summary_dti_interest
```

```{r}
#This is a histogram of the annual income vs the installments
hist(dti_interest$residuals, main = "Histogram of DTI / Interest Rate")

```

```{r}
#This shows the qqplot of installment vs annual income
qqPlot(dti_interest$residuals,
       id = FALSE)

```

```{r}
loanamount_interest <- aov(int_rate ~ loan_amnt,
               data = df)
               
summary_loanamount_interest <- summary(loanamount_interest)

summary_loanamount_interest

```

```{r}
#This is a histogram of the annual income vs the installments
hist(loanamount_interest$residuals, main = "Loan Amount / Interest Rate")

```

```{r}
#This shows the qqplot of installment vs annual income
qqPlot(loanamount_interest$residuals,
       id = FALSE)

```

```{r}
annualinc_interest <- aov(int_rate ~ annual_inc,
               data = df
)
annualinc_interest_sum <- summary(annualinc_interest)
annualinc_interest_sum
```

```{r}
#This is a histogram of the annual income vs the installments
hist(annualinc_interest$residuals, main = "Annual Income / Interest Rate")

```

```{r}
#This shows the qqplot of installment vs annual income
qqPlot(annualinc_interest$residuals,
       id = FALSE)

```

```{r}
installments_interest <- aov(int_rate ~ installment,
               data = df
)
installments_interest_sum <- summary(installments_interest)
installments_interest_sum
```

```{r}
#This is a histogram of the annual income vs the installments
hist(installments_interest$residuals, main = "Installment / Interest Rate")

```

```{r}
#This shows the qqplot of installment vs annual income
qqPlot(installments_interest$residuals,
       id = FALSE)

```

```{r}
totalpmnt_interest <- aov(int_rate ~ total_pymnt,
               data = df
)
summary_totalpmnt <- summary(totalpmnt_interest)

# Extract the residual standard error
summary_totalpmnt
```

```{r}
#This is a histogram of the annual income vs the installments
hist(totalpmnt_interest$residuals, main = "Histogram of Total Payment / Interest Rate")

```

```{r}
#This shows the qqplot of installment vs annual income
qqPlot(totalpmnt_interest$residuals,
       id = FALSE)

```